### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Melcus** [thedevdojo/voyager#17]
I've followed the steps exactly, I get to the login page, and when I click sign in, just the icon turns once, and nothing else happens. Am I missing something?

**Comment by josealgardataborges** [comment]
I have exactly the same problem... running Voyager (current version) on Windows with Wamp Server.

**Comment by josealgardataborges** [comment]
I have a empty users table.

If i run 

```
**php artisan migrate**

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2
passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Requ
est, null given, called in C:\wamp64\www\voyager\vendor\laravel\framework\src\Illuminate\Routing\Rou
tingServiceProvider.php on line 60 in C:\wamp64\www\voyager\vendor\laravel\framework\src\Illuminate\
Routing\UrlGenerator.php:103
Stack trace:
#0 C:\wamp64\www\voyager\vendor\laravel\framework\src\Illuminate\Routing\RoutingServiceProvider.php(
60): Illuminate\Routing\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NULL)
#1 C:\wamp64\www\voyager\vendor\laravel\framework\src\Illuminate\Container\Container.php(290): Illum
inate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Appl
ication))
#2 C:\wamp64\www\voyager\vendor\laravel\framework\src\Illuminate\Container\Container.php(746): Illum
inate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundatio in C:\wamp64\w
ww\voyager\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php on line 103
```

**Comment by afsardo** [comment]
Look at the issue #18 , to solve the `php artisan migrate` problem.

**Comment by josealgardataborges** [comment]
@afsardo Done! 

had to do:

```
php artisan migration:reset
php artisan voyager:install

```

And all back to good :)

**Comment by sikrew** [comment]
@josealgardataborges I've done the exact same thing. And it worked too.

**Comment by tnylea** [comment]
Thanks guys, sorry about that. @afsardo You rock man!
