### ISSUE TITLE
Artisan stops working after install

### ISSUE THREAD

**Issue by afsardo** [thedevdojo/voyager#18]
After installing voyager.

`php artisan voyager:install`

If you try to run any command (`php artisan make:model TwitchStream`) it throws an error:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 60 in /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:103
Stack trace:
#0 /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(60): Illuminate\Routing\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NULL)
#1 /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Container/Container.php(290): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application))
#2 /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Illuminate\Container\Container->Illuminate\Container\{closure}(Ob in /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 60 in /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:103
Stack trace:
#0 /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(60): Illuminate\Routing\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NULL)
#1 /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Container/Container.php(290): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application))
#2 /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Illuminate\Container\Container->Illuminate\Container\{closure}(Ob in /home/vagrant/Code/Voyager/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103
```

Because the voyager config file gets published, it is used every time the app is bootstrapped, so it tries to run the asset() function in the config file which excepts a Request object as the second argument and it crashes.

The solution is simply remove the asset() function from the line:
`
    'assets_path' => asset('/vendor/tcg/voyager/assets'),
`
To:
`
    'assets_path' => '/vendor/tcg/voyager/assets',
`

And actually everything works because there is no need to use the function.

I will send a pull request.

**Comment by tnylea** [comment]
Thanks man. Just merged it an put it in the latest version.
