### ISSUE TITLE
Urgent - Symlink error no image Amazon Elastic Server

### ISSUE THREAD

**Issue by pirocoptero** [thedevdojo/voyager#2259]
- Laravel Version: LAST
- Voyager Version: LAST
- PHP Version: 7
- Database Driver & Version: MYSQL

### Description:
I'am getting symlink error after deploy my app to amazon server. The images is not loading, but in my localhost app is fine. 

### Steps To Reproduce:

![captura de tela 2017-11-20 as 22 27 50](https://user-images.githubusercontent.com/4484855/33048456-1440af2a-ce42-11e7-9c37-d0680230dd1e.png)

my filesystems.php

```
'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'region' => env('AWS_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ],

    ],
```

**Comment by fletch3555** [comment]
It's not an error.  It's just informing you that the symlink (between `...../public/storage` and `...../storage/app/public`, which is [required](https://laravel.com/docs/5.5/filesystem#the-public-disk) for the `public` disk to work properly) does not exist.

**Comment by pirocoptero** [comment]
@fletch3555 thanks for your reply. Can you help me to solve it?

**Comment by fletch3555** [comment]
Make sure your voyager config is set up properly (specifically the [disk config](https://github.com/the-control-group/voyager/blob/master/publishable/config/voyager.php#L69)).  I'm not 100% certain, but doing this MAY prevent that popup.

If it doesn't, you can always just create the symlink.  There should be a "fix it" button on the banner.  If that doesn't work, you can ssh into the server and run `artisan storage:link` from the root of your app.

**Comment by pirocoptero** [comment]
``
sudo php artisan storage:link
PHP Notice:  Undefined index: RDS_HOSTNAME in /var/app/current/config/database_old.php on line 3
PHP Notice:  Undefined index: RDS_USERNAME in /var/app/current/config/database_old.php on line 4
PHP Notice:  Undefined index: RDS_PASSWORD in /var/app/current/config/database_old.php on line 5
PHP Notice:  Undefined index: RDS_DB_NAME in /var/app/current/config/database_old.php on line 6


  [ErrorException]
  symlink(): No such file or directory

``

**Comment by pirocoptero** [comment]
@fletch3555, i tried to do it, but i get this error

```
udo php artisan storage:link
PHP Notice:  Undefined index: RDS_HOSTNAME in /var/app/current/config/database.php on line 3
PHP Notice:  Undefined index: RDS_USERNAME in /var/app/current/config/database.php on line 4
PHP Notice:  Undefined index: RDS_PASSWORD in /var/app/current/config/database.php on line 5
PHP Notice:  Undefined index: RDS_DB_NAME in /var/app/current/config/database.php on line 6


  [ErrorException]
  symlink(): No such file or directory
```

**Comment by pirocoptero** [comment]
The log from aplicattion: 

```
symlink(): No such file or directory {"userId":2,"email":"piro@outlook.com.br","exception":"[object] (ErrorException(code: 0): symlink(): No such file or directory at /var/app/current/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:228)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'symlink(): No s...', '/var/app/curren...', 228, Array)
#1 /var/app/current/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(228): symlink('/var/app/curren...', '/var/app/curren...')
#2 /var/app/current/vendor/tcg/voyager/src/VoyagerServiceProvider.php(164): Illuminate\\Filesystem\\Filesystem->link('/var/app/curren...', '/var/app/curren...')
#3 /var/app/current/vendor/tcg/voyager/src/VoyagerServiceProvider.php(151): TCG\\Voyager\\VoyagerServiceProvider->fixMissingStorageSymlink()
#4 /var/app/current/vendor/tcg/voyager/src/VoyagerServiceProvider.php(105): TCG\\Voyager\\VoyagerServiceProvider->addStorageSymlinkAlert()
#5 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(349): TCG\\Voyager\\VoyagerServiceProvider->TCG\\Voyager\\{closure}()
#6 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('voyager.alerts....', Array)
#7 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(463): Illuminate\\Events\\Dispatcher->dispatch('voyager.alerts....')
#8 /var/app/current/vendor/tcg/voyager/src/Voyager.php(243): event('voyager.alerts....')
#9 /var/app/current/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): TCG\\Voyager\\Voyager->alerts()
#10 /var/app/current/vendor/tcg/voyager/src/VoyagerServiceProvider.php(128): Illuminate\\Support\\Facades\\Facade::__callStatic('alerts', Array)
#11 /var/app/current/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(164): TCG\\Voyager\\VoyagerServiceProvider->TCG\\Voyager\\{closure}(Object(Illuminate\\View\\View))
#12 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Illuminate\\View\\Factory->Illuminate\\View\\Concerns\\{closure}('composing: voya...', Array)
#13 /var/app/current/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('composing: voya...', Array)
#14 /var/app/current/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(179): Illuminate\\Events\\Dispatcher->dispatch('composing: voya...', Array)
#15 /var/app/current/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\\View\\Factory->callComposer(Object(Illuminate\\View\\View))
#16 /var/app/current/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#17 /var/app/current/vendor/laravel/framework/src/Illuminate/Http/Response.php(39): Illuminate\\View\\View->render()
#18 /var/app/current/vendor/symfony/http-foundation/Response.php(201): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#19 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(711): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View))
#20 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#21 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(645): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#22 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/app/current/vendor/tcg/voyager/src/Http/Middleware/VoyagerAdminMiddleware.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): TCG\\Voyager\\Http\\Middleware\\VoyagerAdminMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/app/current/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/app/current/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/app/current/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/app/current/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(647): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#46 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#47 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(588): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#48 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(577): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#49 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#50 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/app/current/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#68 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#69 /var/app/current/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#70 {main}
"}

```

**Comment by pirocoptero** [comment]
Somebody can help me please?

**Comment by fletch3555** [comment]
When you look at this line, does it show you the full path in the logs?

```
#1 /var/app/current/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(228): symlink('/var/app/curren...', '/var/app/curren...')
```

If not, please create the directories.  If so, please check, both paths to make sure they exist and have the appropriate permissions (owner/group should match webserver's user and/or group, with the matching one having read/write privs)

**Comment by pirocoptero** [comment]
Please @fletch3555 help me =/

The permissions 

```

drwxr-xr-x  6 webapp webapp   4096 Nov  8 17:15 public
drwxr-xr-x  5 webapp webapp   4096 Set 26 18:53 resources
drwxr-xr-x  2 webapp webapp   4096 Nov  8 17:19 routes
-rw-r--r--  1 webapp webapp    563 Set 24 01:29 server.php
drwxr-xr-x  5 webapp webapp   4096 Out 12 17:09 storage

```

**Comment by pirocoptero** [comment]
@fletch3555 

Have you ever set up voyager on amazon aws server?

**Comment by fletch3555** [comment]
I have not personally, but I know it can be done.

There are too many variables at play for me to just guess at the solution.  The error has something to do with the creation of that symlink, which is an action Voyager takes, but not one Voyager manages.  Voyager simply calls `artisan storage:link`, which then does the work.  There are a number of possible causes:

1. your server does not have `symlink()` enabled for PHP (a security measure usually taken on shared hosts, not likely the case in your instance)
2. you've installed laravel in a non-standard way (i.e. moved the public directory instead of setting up your web server's vhost correctly)
3. similar to number 2, the directory does not exist (the public directory is expected to be called `public` and live directly under your app root, and the `storage/app/public` directory is expected to exist as well)
4. both of the above mentioned directories are expected to be readable by the account the web server is running under (commonly `www-data` or `apache`), and the `public` directory must also be writable by that account in order to create the symlink

If you still have issues, you may have better luck in larachat's #servers room

**Comment by marktopper** [comment]
I am using Voyager with AWS S3 without any issues.
Do you still have those issues?

**Comment by emptynick** [comment]
Closing due to inactivity.
