### ISSUE TITLE
bootstrap-datetimepicker: Cannot read property 'addClass' of undefined

### ISSUE THREAD

**Issue by defaultpage** [thedevdojo/voyager#2686]
- Laravel Version: 5.5.34
- Voyager Version: 1.0.15
- PHP Version: 7.1
- Database Driver & Version: MySQL
- **Browser**: Chrome 63.0.3239.132 (dev, 64bit)
- **System**: Windows 10

### Description:
I don't change anyone `edit` view...
<details>
<summary>
Error
</summary>

```console
jQuery.Deferred exception: Cannot read property 'addClass' of undefined TypeError: Cannot read property 'addClass' of undefined
    at o.init (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:77:1615)
    at new o (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:77:856)
    at HTMLInputElement.<anonymous> (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:77:16669)
    at Function.each (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:14:14819)
    at ye.fn.init.each (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:14:13082)
    at ye.fn.init.e.fn.datetimepicker (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:77:16559)
    at HTMLDocument.<anonymous> (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:24:100854)
    at c (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:24:25135)
    at u (https://partner.smfamily.ru/vendor/tcg/voyager/assets/js/app.js:24:25449) undefined
ye.Deferred.exceptionHook @ app.js:24
```
</details>

________

[Link](https://habrastorage.org/webt/qg/ma/cq/qgmacqasa4uzetotrxsv-t_78qo.png)
![](https://habrastorage.org/webt/qg/ma/cq/qgmacqasa4uzetotrxsv-t_78qo.png)

### Steps To Reproduce:
1. Install Laravel 5.5.34
2. Install Voyager 1.0.15
3. Create bread with editable timestamps
4. Try to edit row of the new bread.

**Comment by defaultpage** [comment]
Wow... I'm sorry. This is duplicate (#1806). You can find temporary solution in comments.
