### ISSUE TITLE
Voyager and SQL Server: Platform Mssql doesn't exist

### ISSUE THREAD

**Issue by sudinem** [thedevdojo/voyager#3225]
- Laravel Version: 5.4
- Voyager Version: 1.1
- PHP Version: 5.6.12
- Database Driver & Version:
SQL Server

Description:
I have used SQL server with voyager. The installation and everything works fine but when I access the BREAD, database edit page. It shows the following error:

(1/1) Exception
Platform Mssql doesn't exist

**Comment by fletch3555** [comment]
Please provide the full stacktrace.

**Comment by sudinem** [comment]
![fireshot capture 17 - - http___localhost_8000_admin_database_menus_edit](https://user-images.githubusercontent.com/8023276/40584106-36c8e62c-61bb-11e8-842e-7beab0d0b98c.png)

**Comment by fletch3555** [comment]
Would you mind getting the stacktrace from the logs instead so I can see full namespaces?

**Comment by sudinem** [comment]
Here it is:

```
[2018-05-27 13:12:30] local.ERROR: Exception: Platform Mssql doesn't exist in D:\wamp64\www\company\vendor\tcg\voyager\src\Database\Platforms\Platform.php:18
Stack trace:
#0 D:\wamp64\www\company\vendor\tcg\voyager\src\Database\Platforms\Platform.php(33): TCG\Voyager\Database\Platforms\Platform::getPlatform('Mssql')
#1 D:\wamp64\www\company\vendor\tcg\voyager\src\Database\Types\Type.php(115): TCG\Voyager\Database\Platforms\Platform::registerPlatformCustomTypeOptions('Mssql')
#2 D:\wamp64\www\company\vendor\tcg\voyager\src\Database\Types\Type.php(106): TCG\Voyager\Database\Types\Type::addCustomTypeOptions('Mssql')
#3 D:\wamp64\www\company\vendor\tcg\voyager\src\Database\Schema\SchemaManager.php(77): TCG\Voyager\Database\Types\Type::registerCustomPlatformTypes()
#4 D:\wamp64\www\company\vendor\tcg\voyager\src\Http\Controllers\VoyagerBreadController.php(118): TCG\Voyager\Database\Schema\SchemaManager::describeTable('menus')
#5 [internal function]: TCG\Voyager\Http\Controllers\VoyagerBreadController->edit('menus')
#6 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#7 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('edit', Array)
#8 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Voyager\VoyagerBreadController), 'edit')
#9 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#10 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Router.php(572): Illuminate\Routing\Route->run()
#11 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 D:\wamp64\www\company\vendor\tcg\voyager\src\Http\Middleware\VoyagerAdminMiddleware.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): TCG\Voyager\Http\Middleware\VoyagerAdminMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#38 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 D:\wamp64\www\company\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#54 D:\wamp64\www\company\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#55 D:\wamp64\www\company\server.php(21): require_once('D:\\wamp64\\www\\n...')
#56 {main}  
```

**Comment by fletch3555** [comment]
Thank you. That just confirmed my suspicion. Voyager does not currently support mssql.  There's no platform or type for it.  We're certainly open to pull requests if you wish to make it.

**Comment by sudinem** [comment]
Are you planning to make a release for SQL server database.

**Comment by marcellopato** [comment]
Does Voyager supports MSSQL now?

**Comment by fletch3555** [comment]
No. And please don't comment on old closed issues.
