### ISSUE TITLE
User file wiped when visiting Media section

### ISSUE THREAD

**Issue by OctaneInteractive** [thedevdojo/voyager#3626]
## Version information

 - Laravel: v5.6.38
 - Voyager: v1.1.3
 - PHP: 7.1.8-2
 - Database: MySQL 14.14 Distrib 5.7.23

## Description

In the last week I made an update to both Laravel and Voyager for an existing application.

While attempting to upload images via Media a user encountered an error.

![image](https://user-images.githubusercontent.com/419501/46864293-d77f2500-ce11-11e8-886f-e71b7d30247a.png)

After navigating to the Dashboard the user then got another error:

> Class 'App\User' not found

... on line 85 of "tcg/voyager/src/VoyagerServiceProvider.php"

I then followed the instructions in the documentation, checking the "conf.php" files before then looking at the "User.php" file itself, and it was then when I discovered the file had been written blank, with Git tracking it as a change.

## Steps To Reproduce

Now, each time we go to Media it wipes the "User.php" file and I have to copy and paste into it again from the source to get the application working.

**Comment by fletch3555** [comment]
I can't think of any reason for that unless something is misconfigured in your app.  Unfortunately, there are about a billion too many permutations for me to guess at the cause.  Can you attempt to narrow down a reproducible case for us?

**Comment by OctaneInteractive** [comment]
Hi @fletch3555, I've not made changes to Media, and I'm using the basic configurations, based on the instructions for Voyager.

What configurations would you expect to be the cause?

In terms of narrowing things down, this is as narrow as it gets:
1. click on Media;
2. "User.php" is emptied.

**Comment by OctaneInteractive** [comment]
I've tried again this morning, and while the behaviour is the same, it's now not possible to restore the file with a copy and paste via FTP and I have to use Git instead.

**Comment by OctaneInteractive** [comment]
I ran the whole thing again using the `tail` command, and this is the error for that event:
```
[2018-10-15 07:51:10] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/project/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:181)
[stacktrace]
#0 /var/www/project/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(115): Illuminate\\Log\\LogManager->resolve(NULL)
#1 /var/www/project/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(103): Illuminate\\Log\\LogManager->get(NULL)
#2 /var/www/project/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(526): Illuminate\\Log\\LogManager->driver()
#3 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(113): Illuminate\\Log\\LogManager->error('Class 'App\\\\User...', Array)
#4 /var/www/project/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#5 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#6 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#7 /var/www/project/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#8 {main}
"} 
[2018-10-15 07:51:10] laravel.ERROR: Class 'App\User' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\User' not found at /var/www/project/vendor/tcg/voyager/src/VoyagerServiceProvider.php:85)
[stacktrace]
#0 [internal function]: TCG\\Voyager\\VoyagerServiceProvider->boot(Object(Illuminate\\Routing\\Router), Object(Illuminate\\Events\\Dispatcher))
#1 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /var/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(794): Illuminate\\Container\\Container->call(Array)
#6 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(777): Illuminate\\Foundation\\Application->bootProvider(Object(TCG\\Voyager\\VoyagerServiceProvider))
#7 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(TCG\\Voyager\\VoyagerServiceProvider), 23)
#8 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(778): array_walk(Array, Object(Closure))
#9 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#10 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#11 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#12 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#13 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#14 /var/www/project/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#15 {main}
"}
```

**Comment by OctaneInteractive** [comment]
I ran the command: `inotifywatch -v -e access -e modify User.php` and got:

```
Establishing watches...
Total of 1 watches.
Finished establishing watches, now collecting statistics.
total  access  modify  filename
80     22      58      User.php
```

So the "User.php" file was accessed 22 times and modified 58 times.

**Comment by OctaneInteractive** [comment]
Something else worth mentioning, and although the conditional in the `__construct()` method is a fix to something I do remember finding in the workspace for Voyager on Slack, I don't remember what the problem was, but this is the "User.php" file:

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends \TCG\Voyager\Models\User
{
    use Notifiable;

    public function __construct(array $attributes = [])
	{

		parent::__construct($attributes);

		if (file_exists(app_path('User.php'))) {
			$str = file_get_contents(app_path('User.php'));
			if ($str !== false) {
				$str = str_replace('extends \TCG\Voyager\Models\User', "extends \TCG\Voyager\Models\User", $str);
				file_put_contents(app_path('User.php'), $str);
			}
		} else {
			$this->warn('Unable to locate "app/User.php". Did you move this file?');
			$this->warn('You will need to update this manually.  Change "extends \TCG\Voyager\Models\User" to "extends \TCG\Voyager\Models\User" in your User model');
		}

	}

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```
Because I'd forgotten, I didn't think to look at the file itself.

**Comment by MrCrayon** [comment]
I guess you found the problem. 
Please don't use such things in your __construct method, that's something that should be checked at install or changed manually. 

If you are still experiencing this problem in current Voyager release please open another issue.
