### ISSUE TITLE
404 error when trying to delete menu item

### ISSUE THREAD

**Issue by nixprosoft** [thedevdojo/voyager#4704]
## Version information
 - Laravel: v6.11.0
 - Voyager: v1.3.1
 - PHP: 7.3
 - Database: MySQL 5.7

## Description:
On page /admin/menus/2/builder try to click Delete button, after confirmation got 404 error page.
DELETE method goes to /admin/menus/2/item/__id/16
This route does not exist.

## Additional context
![image](https://user-images.githubusercontent.com/5313478/72545459-195f0c80-389a-11ea-9b70-8d42fbf122d4.png)
![image](https://user-images.githubusercontent.com/5313478/72545524-385d9e80-389a-11ea-965d-921d0875c457.png)

**Comment by nixprosoft** [comment]
path should be `/admin/menus/2/item/16` instead of `/admin/menus/2/item/__id/16`

route is

```
 | web,admin.user |
|        | DELETE    | admin/menus/{menu}/item/{id}         | voyager.menus.item.destroy        | TCG\Voyager\Http\Controllers\VoyagerMenuController@delete_menu
```
\vendor\tcg\voyager\resources\views\menus\builder.blade.php
![image](https://user-images.githubusercontent.com/5313478/72546151-4f50c080-389b-11ea-9e20-60b0b171f32c.png)

**Comment by nixprosoft** [comment]
Ah, it's already fixed. I have semifixed version in my app \resources\views\vendor\voyager\menus

**Comment by nixprosoft** [comment]
Sorry, now I got 500
```
[previous exception] [object] (Illuminate\\Routing\\Exceptions\\UrlGenerationException(code: 0): Missing required parameters for [Route: voyager.menus.item.destroy] [URI: admin/menus/{menu}/item/{id}]. at /var/www/u0893642/data/www/xn----8sbntcghigbfnkr3n.xn--p1ai/vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:17)
[stacktrace]
#0 /var/www/u0893642/data/www/xn----8sbntcghigbfnkr3n.xn--p1ai/vendor/laravel/framework/src/Illuminate/Routing/RouteUrlGenerator.php(91): Illuminate\\Routing\\Exceptions\\UrlGenerationException::forMissingParameters(Object(Illuminate\\Routing\\Route))
#1 /var/www/u0893642/data/www/xn----8sbntcghigbfnkr3n.xn--p1ai/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(436): Illuminate\\Routing\\RouteUrlGenerator->to(Object(Illuminate\\Routing\\Route), Array, true)
#2 /var/www/u0893642/data/www/xn----8sbntcghigbfnkr3n.xn--p1ai/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(417): Illuminate\\Routing\\UrlGenerator->toRoute(Object(Illuminate\\Routing\\Route), Array, true)
#3 /var/www/u0893642/data/www/xn----8sbntcghigbfnkr3n.xn--p1ai/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(782): Illuminate\\Routing\\UrlGenerator->route('voyager.menus.i...', Array, true)
#4 /var/www/u0893642/data/www/xn----8sbntcghigbfnkr3n.xn--p1ai/storage/framework/views/212dfc0b3fc01745ea5aba56a4bdc5b614d792f8.php(284): route('voyager.menus.i...', Array)

```

because of this

![image](https://user-images.githubusercontent.com/5313478/72547335-832ce580-389d-11ea-9cac-f65c6e0a3e8e.png)

**Comment by nixprosoft** [comment]
Argh... local version not updated. Sorry.

Works fine
