### ISSUE TITLE
Many-to-Many relation does show "no result"

### ISSUE THREAD

**Issue by titicaca37** [thedevdojo/voyager#4845]
## Version information

 - Laravel: v6.2 (not v5.8  as previously mentioned)
 - Voyager: v3.1.2
 - PHP: 7.2
 - Database: MySQL 5.7

## Description:
After upgrade to v3.1.2 the many-to-many relationship just shows "no result". After downgrade to v3.1.1 the many-to-many entries are shown again. 

## Additional context
When editing an entry, the autocomplete for the many-to-many relationship is still working in v3.1.2, yet on save an exception is thrown.

**Comment by MrCrayon** [comment]
Do you have custom templates or controllers?

Can you take a screenshot from your browser network tab for the ajax call made to populate relationship field? (headers and response)

> When editing an entry, the autocomplete for the many-to-many relationship is still working in v3.1.2, yet on save an exception is thrown.

Which exception?

**Comment by titicaca37** [comment]
No custom voyager controllers or voyager templates. 

To take the screenshot I just upgraded to 3.1.2 again and reverted the DB with a dump from 2020-03-29 19:10:00 (before the Exception).First everything also worked with 3.1.2. After clearing the cache (view, route, config), the error occurs again.  After downgrading to 3.1.1 and clearing the view cache the error is gone. again.  

![voyager1](https://user-images.githubusercontent.com/3640505/77896717-fe851d00-7278-11ea-9520-cd8196e10efe.jpg)


AJAX: Response: 
```
{"pub_id":{"name":"pub_id","type":"bigint","default":null,"notnull":true,"length":null,"precision":10,"scale":0,"fixed":false,"unsigned":true,"autoincrement":true,"columnDefinition":null,"comment":null,"oldName":"pub_id","null":"NO","extra":"auto_increment","composite":false,"field":"pub_id","indexes":{"PRIMARY":{"name":"PRIMARY","oldName":"PRIMARY","columns":["pub_id"],"type":"PRIMARY","isPrimary":true,"isUnique":true,"isComposite":false,"flags":[],"options":{"lengths":[null]}}},"key":"PRI"},"pub_pmid":{"name":"pub_pmid","type":"bigint","default":null,"notnull":false,"length":null,"precision":10,"scale":0,"fixed":false,"unsigned":true,"autoincrement":false,"columnDefinition":null,"comment":null,"oldName":"pub_pmid","null":"YES","extra":"","composite":false,"field":"pub_pmid","indexes":[],"key":null},"pub_agent_id":{"name":"pub_agent_id","type":"bigint","default":null,"notnull":true,"length":null,"precision":10,"scale":0,"fixed":false,"unsigned":true,"autoincrement":false,"columnDefinition":null,"comment":null,"oldName":"pub_agent_id","null":"NO","extra":"","composite":false,"field":"pub_agent_id","indexes":[],"key":null},"pub_orig_string":{"name":"pub_orig_string","type":"varchar","default":null,"notnull":true,"length":191,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_orig_string","null":"NO","extra":"","composite":false,"field":"pub_orig_string","indexes":[],"key":null},"pub_published_at":{"name":"pub_published_at","type":"varchar","default":null,"notnull":false,"length":191,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_published_at","null":"YES","extra":"","composite":false,"field":"pub_published_at","indexes":[],"key":null},"pub_author":{"name":"pub_author","type":"varchar","default":null,"notnull":false,"length":799,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_author","null":"YES","extra":"","composite":false,"field":"pub_author","indexes":[],"key":null},"pub_title":{"name":"pub_title","type":"varchar","default":null,"notnull":false,"length":1400,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_title","null":"YES","extra":"","composite":false,"field":"pub_title","indexes":[],"key":null},"pub_publisher":{"name":"pub_publisher","type":"varchar","default":null,"notnull":false,"length":191,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_publisher","null":"YES","extra":"","composite":false,"field":"pub_publisher","indexes":[],"key":null},"pub_volume_issue":{"name":"pub_volume_issue","type":"varchar","default":null,"notnull":false,"length":191,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_volume_issue","null":"YES","extra":"","composite":false,"field":"pub_volume_issue","indexes":[],"key":null},"pub_ref_page":{"name":"pub_ref_page","type":"varchar","default":null,"notnull":false,"length":191,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_ref_page","null":"YES","extra":"","composite":false,"field":"pub_ref_page","indexes":[],"key":null},"pub_abstract":{"name":"pub_abstract","type":"text","default":null,"notnull":false,"length":65535,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_abstract","null":"YES","extra":"","composite":false,"field":"pub_abstract","indexes":[],"key":null},"pub_doi":{"name":"pub_doi","type":"varchar","default":null,"notnull":false,"length":191,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"charset":"utf8mb4","collation":"utf8mb4_unicode_ci","oldName":"pub_doi","null":"YES","extra":"","composite":false,"field":"pub_doi","indexes":[],"key":null},"created_at":{"name":"created_at","type":"timestamp","default":null,"notnull":false,"length":0,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"oldName":"created_at","null":"YES","extra":"","composite":false,"field":"created_at","indexes":[],"key":null},"updated_at":{"name":"updated_at","type":"timestamp","default":null,"notnull":false,"length":0,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"oldName":"updated_at","null":"YES","extra":"","composite":false,"field":"updated_at","indexes":[],"key":null},"pub_year":{"name":"pub_year","type":"year","default":null,"notnull":false,"length":null,"precision":10,"scale":0,"fixed":false,"unsigned":false,"autoincrement":false,"columnDefinition":null,"comment":null,"oldName":"pub_year","null":"YES","extra":"","composite":false,"field":"pub_year","indexes":[],"key":null}}
```
```
[2020-03-29 20:07:55] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'agent_agent_id' cannot be null (SQL: insert into `agent_publication` (`agent_agent_id`, `publication_pub_id`) values (?, 1)) {"userId":2,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'agent_agent_id' cannot be null (SQL: insert into `agent_publication` (`agent_agent_id`, `publication_pub_id`) values (?, 1)) at /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
[stacktrace]
#0 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('insert into `ag...', Array, Object(Closure))
#1 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\\Database\\Connection->run('insert into `ag...', Array, Object(Closure))
#2 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\\Database\\Connection->statement('insert into `ag...', Array)
#3 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2651): Illuminate\\Database\\Connection->insert('insert into `ag...', Array)
#4 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(256): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(160): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->attach(1, Array, false)
#6 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(112): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->attachNew(Array, Array, false)
#7 /home/vagrant/code/phototox/vendor/tcg/voyager/src/Http/Controllers/Controller.php(156): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->sync(Array)
#8 /home/vagrant/code/phototox/vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php(328): TCG\\Voyager\\Http\\Controllers\\Controller->insertUpdateData(Object(Illuminate\\Http\\Request), 'agents', Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Agent))
#9 [internal function]: TCG\\Voyager\\Http\\Controllers\\VoyagerBaseController->update(Object(Illuminate\\Http\\Request), '207')
#10 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#11 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)
#12 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(TCG\\Voyager\\Http\\Controllers\\VoyagerBaseController), 'update')
#13 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#14 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#15 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/vagrant/code/phototox/vendor/tcg/voyager/src/Http/Middleware/VoyagerAdminMiddleware.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): TCG\\Voyager\\Http\\Middleware\\VoyagerAdminMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#33 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#34 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#35 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#36 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/vagrant/code/phototox/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 /home/vagrant/code/phototox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#50 /home/vagrant/code/phototox/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#51 {main}
```

**Comment by MrCrayon** [comment]
Can you post what's saved in db for relationship's field in `data_rows.details`?

It has probably something to do with the fact that you are using `agent_id` as primary key in agents table and while before #4702 you could only use primary key as reference now that you can choose it's using `$options->key` that might have been saved as "id" by default.

If that's the problem you might try to check what do you see while editing that relationship in BREAD and if it looks normal hit save and that might solve the problem, otherwise you need to set the correct field in BREAD and save.

Please report what's in db and steps required to fix if my suggestion works so that we might add it to documentation for 1.4

**Comment by titicaca37** [comment]
Yes, the primaray key "table_name"-ID seems to be the problem. The user_belongstomany_role_relationship works. 

My data_rows.details: 
{"model":"App\\Publication","table":"publications","type":"belongsToMany","column":"agent_id","key":"pub_id","label":"pub_orig_string","pivot_table":"agent_publication","pivot":"1","taggable":"0"}

My table structure: 
- Table agents with agent_id as primary key
- Table publications with pub_id as primary key
- agent_publication as pivot table with columns agent_agent_id and publication_pub_id

My AgentController with:
 ```
... 
protected $primaryKey = 'agent_id';

public function publications()
    {
        return $this->belongsToMany('App\Publication', 'agent_publication', 'agent_agent_id', 'publication_pub_id');
    }
```
I tried various combination of other column names, yet I belive my naming with agent_agent_id and publication_pub_id (in the pivot talbe) if the primary key is renamed in Laravel is the correct way.

**Comment by MrCrayon** [comment]
I'll need to replicate to see what's going wrong. 
My first thought was a problem on updating from 1.3.1 to 1.3.2 but it looks like you already tried to recreate the relationship. 

Untill I find the time to test it you can check what's wrong on saving here:
https://github.com/the-control-group/voyager/blob/7af8ae189dd8100bd201b0325710be3d68a753b8/src/Http/Controllers/Controller.php#L117

**Comment by MrCrayon** [comment]
Looks like I switched parent_key for related_key, this should fix it:
![Schermata da 2020-04-03 13-19-19](https://user-images.githubusercontent.com/6875243/78355365-ddd90200-75ad-11ea-9959-e52fbdd8bff1.png)
![Schermata da 2020-04-03 13-19-30](https://user-images.githubusercontent.com/6875243/78355376-e03b5c00-75ad-11ea-8081-bdb4902ed741.png)

**Comment by titicaca37** [comment]
Thanks. With your fix it is now possible to save the many to many relationship, i.e. they exist in the Database.  
Yet existing relations in the database are not displayed in Voyager (neither in View nor Edit) and when saving in Voyager are overwritten/deleted in the database. 
I also just realized, I use Laravel 6.2 and not 5.8 as previsouly mentioned. Mixed up the projects. Sorry.

**Comment by MrCrayon** [comment]
Did you apply the changes to `relationship.blade`? 
If yes try clearing views cache.

**Comment by titicaca37** [comment]
Its working now. Thanks for your effort. 
Had to revert and make the changes again. Probably had a typo somewhere.

**Comment by MrCrayon** [comment]
Thanks for reporting, I'll open a PR as soon as possible.
