### ISSUE TITLE
Voyager Error After update from [1.3] to [1.4]

### ISSUE THREAD

**Issue by odion-cloud** [thedevdojo/voyager#5076]
## Version information

 - Laravel: v7.26
 - Voyager: v1.4
 - PHP: 7.4.7
 - Database: [MySQL] [7.4.7]

## Description:
**GET http://domain.org/admin/voyager-assets?path=js%2Fapp.js net::ERR_ABORTED 500 (Internal Server Error)
admin:277 Uncaught ReferenceError: Vue is not defined at admin:277
(anonymous) @ admin:277** (Voyager Error After update from [1.3] to [1.4])

## Additional context
Hello Voyager Artisan  please out with this issue!
after i update  laravel composer and also voyager laravel From version **[5.8] to [7.26]** 

everything works fine except my laravel-voyager not loading properly and spinner keep spinning 
I have done everything i can but to no good result
this is the display image below
![voyagererror](https://user-images.githubusercontent.com/57910372/92993607-d0279100-f4ea-11ea-8a47-2fa82b89cdd2.PNG)

**Comment by emptynick** [comment]
There are some issue with the exact same problem.
It's very likely a problem with an extension in your browser, another laravel package or the browser itself.
Check if it's working in incognito mode, check your Laravel logs, and try it in a different browser.

**Comment by odion-cloud** [comment]
> There are some issue with the exact same problem.
> It's very likely a problem with an extension in your browser, another laravel package or the browser itself.
> Check if it's working in incognito mode, check your Laravel logs, and try it in a different browser.

Thank for Repply @emptynick 
i have tried it on Opera Browers,Firefox for dev and chrome incognito mode and error still coming out nothing change

**Comment by emptynick** [comment]
And the logs?

**Comment by odion-cloud** [comment]
> And the logs?

(error from firefox)
GEThttp://domain.org/admin/voyager-assets?path=js%2Fapp.js
[HTTP/1.0 500 Internal Server Error 5363ms]

Uncaught ReferenceError: Vue is not defined
    <anonymous> http://domain.org/admin#:277

(log from firefox)
XHR GEThttps://content.googleapis.com/discovery/v1/apis/analytics/v3/rest?fields=kind%2Cname%2Cversion%2CrootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods%2CbatchPath%2Cid&pp=0

**Comment by emptynick** [comment]
I mean the Laravel logs.

**Comment by odion-cloud** [comment]
> I mean the Laravel logs.

this is the error from laravel log

```
[2020-09-12 12:06:11] local.ERROR: Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable CSRF protection on this action to permit cross-origin JavaScript embedding. {"userId":1,"exception":"[object] (Efficiently\\JqueryLaravel\\CrossOriginRequestException(code: 0): Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable CSRF protection on this action to permit cross-origin JavaScript embedding. at C:\\xampp\\htdocs\\Churchaut\\vendor\\efficiently\\jquery-laravel\\src\\Efficiently\\JqueryLaravel\\VerifyJavascriptResponse.php:48)
[stacktrace]
#0 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Efficiently\\JqueryLaravel\\VerifyJavascriptResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#1 C:\\xampp\\htdocs\\Churchaut\\vendor\\barryvdh\\laravel-stack-middleware\\src\\ClosureHttpKernel.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#2 C:\\xampp\\htdocs\\Churchaut\\vendor\\helthe\\turbolinks\\StackTurbolinks.php(51): Barryvdh\\StackMiddleware\\ClosureHttpKernel->handle(Object(Illuminate\\Http\\Request), 1, true)
#3 C:\\xampp\\htdocs\\Churchaut\\vendor\\barryvdh\\laravel-stack-middleware\\src\\ClosureMiddleware.php(36): Helthe\\Component\\Turbolinks\\StackTurbolinks->handle(Object(Illuminate\\Http\\Request))
#4 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\StackMiddleware\\ClosureMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#5 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#6 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#7 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 C:\\xampp\\htdocs\\Churchaut\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#17 C:\\xampp\\htdocs\\Churchaut\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#18 {main}
"}
```

**Comment by emptynick** [comment]
There are two problems here:
1. The package `Efficiently\JqueryLaravel` forbids accessing our Javascript file (not sure why it thinks it's responsible to do that)
2. The package fails because it sees the request for that file coming from another domain. This can be because you are using https and the route to the file is generated as http.

None of those are related to Voyager.
