### ISSUE TITLE
after upgrade 1.4.3 , voyager excel test case is failed 

### ISSUE THREAD

**Issue by tu6ge** [thedevdojo/voyager#5439]
### Laravel version

7

### PHP version

7.3

### Voyager version

1.4.3

### Database

-

### Description

Hi, I find the last version suport php 8, and today, I am changing github workflows , voyager excel plugin `s test case is failed ,[more info](https://github.com/tu6ge/voyager-excel/runs/3455019787?check_suite_focus=true)

### Steps to reproduce

run github workflow

### Expected behavior

run test case success

**Comment by tu6ge** [comment]
error info:
```
PHP Warning:  Uncaught ErrorException: require_once(/home/tu6ge/php/voyager-excel/vendor/orchestra/testbench-core/laravel/vendor/autoload.php): failed to open stream: No such file or directory in /home/tu6ge/php/voyager-excel/vendor/tcg/voyager/src/Commands/InstallCommand.php:146
Stack trace:
#0 /home/tu6ge/php/voyager-excel/vendor/tcg/voyager/src/Commands/InstallCommand.php(146): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/tu6ge/php/voyager-excel/vendor/tcg/voyager/src/Commands/InstallCommand.php(146): require_once()
#2 /home/tu6ge/php/voyager-excel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): TCG\Voyager\Commands\InstallCommand->handle()
#3 /home/tu6ge/php/voyager-excel/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /home/tu6ge/php/voyager-excel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#5 /home/tu6ge/php/voy in /home/tu6ge/php/voyager-excel/vendor/tcg/voyager/src/Commands/InstallCommand.php on line 146
PHP Fatal error:  TCG\Voyager\Commands\InstallCommand::handle(): Failed opening required '/home/tu6ge/php/voyager-excel/vendor/orchestra/testbench-core/laravel/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/tu6ge/php/voyager-excel/vendor/tcg/voyager/src/Commands/InstallCommand.php on line 146
```

**Comment by MrCrayon** [comment]
Changes have been made to make seeders work in Laravel 8, you probably need to update your TestCase.
Relevant changes should be here #5093
